### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by Commandcracker** [CC-YouCube/server#1]
### Describe the feature.

Clear cache after a while.

**Comment by tomodachi94** [comment]
I think this would best fit as an external tool that could get called periodically through systemd or cron, see https://12factor.net/admin-processes. I can take a shot at writing it :)

**Comment by Commandcracker** [comment]
Now I'm disappointed with my self ._.
`OSError: [Errno 28] No space left on device: '/tmp/youcube-h10dm688'`
```
Filesystem                Size      Used Available Use% Mounted on
overlay                 465.9G    446.3G         0 100% /
```
